name: Check repository

on:
  repository_dispatch:
    types: [announce-repository]

  workflow_dispatch:
    inputs:
      repository:
        type: string
        required: true
      template:
        type: string
        required: true
      flags:
        type: string
        required: false

jobs:
  announce-repository:
    name: announce repository
    if: |
      github.repository == 'iobroker-bot-orga/announce'
      
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install --omit=dev

      - name: announce repository
        run: node ./announceRepository.js ${{ github.event.inputs.repository }} ${{ github.event.client_payload.url }} --template="${{ github.event.inputs.template }}${{ github.event.client_payload.url }}" ${{ github.event.inputs.flags }}${{ github.event.client_payload.flags }}
        env:
          IOBBOT_GITHUB_TOKEN: ${{ secrets.IOBBOT_GITHUB_TOKEN }}
